/* Generated by re2c 0.16 */
#line 1 "/opt/src/php-cmark/src/cql_lexer.l"
/*
 * cql_lexer.l
 */

#include <src/cql.h>
#include <src/cql_parser.h>

#line 11 "/opt/src/php-cmark/src/cql_lexer.c"

enum cql_lex_state_t {
	ST_LOOKING_FOR_SEPARATOR,
	ST_LOOKING_FOR_NODE,
	ST_LOOKING_FOR_SUBQUERY,
	ST_LOOKING_FOR_TYPE,
	ST_LOOKING_FOR_TYPE_SEPARATOR,
};

#line 8 "/opt/src/php-cmark/src/cql_lexer.l"
struct _cql_lex_t {
        unsigned int len;
        unsigned char *text;
        unsigned char *cursor;
        unsigned char *marker;
        unsigned char *ctxmarker;
        int state;
};

cql_lex_t* cql_lex_init (unsigned char *text, size_t length) {
	cql_lex_t *lex;

	if (!length || !text || !*text) {
		return NULL;
	}

	lex = (cql_lex_t*) calloc(1, sizeof(cql_lex_t));

	if (!lex) {
		return NULL;
	}

	lex->state = ST_LOOKING_FOR_SEPARATOR;
	lex->text  = lex->cursor = text;
	lex->len   = length;

	return lex;
}

unsigned char* cql_lex_cursor(cql_lex_t *lex, int offset) {
	return lex->cursor + offset;
}

void cql_lex_free(cql_lex_t *lex) {
	if (!lex) {
		return;
	}

	free(lex);
}

int cql_lex (cql_ast_t *yylval, cql_lex_t *lex) {

restart:

	lex->text = lex->cursor;


#line 70 "/opt/src/php-cmark/src/cql_lexer.c"
{
	unsigned char yych;
	unsigned int yyaccept = 0;
	if (lex->state < 2) {
		if (lex->state < 1) {
			goto yyc_ST_LOOKING_FOR_SEPARATOR;
		} else {
			goto yyc_ST_LOOKING_FOR_NODE;
		}
	} else {
		if (lex->state < 3) {
			goto yyc_ST_LOOKING_FOR_SUBQUERY;
		} else {
			if (lex->state < 4) {
				goto yyc_ST_LOOKING_FOR_TYPE;
			} else {
				goto yyc_ST_LOOKING_FOR_TYPE_SEPARATOR;
			}
		}
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_NODE:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(10);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy7;
		}
		if (yych <= 'R') {
			if (yych <= 'F') {
				if (yych <= '#') {
					if (yych <= 0x00) goto yy3;
					if (yych <= '"') goto yy5;
					goto yy10;
				} else {
					if (yych == 'C') goto yy11;
					if (yych <= 'E') goto yy5;
					goto yy12;
				}
			} else {
				if (yych <= 'M') {
					if (yych == 'L') goto yy13;
					goto yy5;
				} else {
					if (yych <= 'N') goto yy14;
					if (yych == 'P') goto yy15;
					goto yy5;
				}
			}
		} else {
			if (yych <= 'l') {
				if (yych <= 'c') {
					if (yych <= 'S') goto yy16;
					if (yych <= 'b') goto yy5;
					goto yy11;
				} else {
					if (yych == 'f') goto yy12;
					if (yych <= 'k') goto yy5;
					goto yy13;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'n') goto yy14;
					goto yy5;
				} else {
					if (yych <= 'p') goto yy15;
					if (yych == 's') goto yy16;
					goto yy5;
				}
			}
		}
yy3:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 104 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 183 "/opt/src/php-cmark/src/cql_lexer.c"
yy5:
		++lex->cursor;
yy6:
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 310 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 1;
}
#line 192 "/opt/src/php-cmark/src/cql_lexer.c"
yy7:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy7;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 108 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 205 "/opt/src/php-cmark/src/cql_lexer.c"
yy10:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy17;
		}
		goto yy6;
yy11:
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'H') goto yy20;
		if (yych == 'h') goto yy20;
		goto yy6;
yy12:
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'I') goto yy22;
		if (yych == 'i') goto yy22;
		goto yy6;
yy13:
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'A') goto yy23;
		if (yych == 'a') goto yy23;
		goto yy6;
yy14:
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'E') goto yy24;
		if (yych == 'e') goto yy24;
		goto yy6;
yy15:
		yych = *(lex->marker = ++lex->cursor);
		if (yych <= 'R') {
			if (yych == 'A') goto yy25;
			if (yych <= 'Q') goto yy6;
			goto yy26;
		} else {
			if (yych <= 'a') {
				if (yych <= '`') goto yy6;
				goto yy25;
			} else {
				if (yych == 'r') goto yy26;
				goto yy6;
			}
		}
yy16:
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'I') goto yy27;
		if (yych == 'i') goto yy27;
		goto yy6;
yy17:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy17;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 112 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 264 "/opt/src/php-cmark/src/cql_lexer.c"
yy20:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy28;
		if (yych == 'i') goto yy28;
yy21:
		lex->cursor = lex->marker;
		goto yy6;
yy22:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy29;
		if (yych == 'r') goto yy29;
		goto yy21;
yy23:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy30;
		if (yych == 's') goto yy30;
		goto yy21;
yy24:
		yych = *++lex->cursor;
		if (yych == 'X') goto yy31;
		if (yych == 'x') goto yy31;
		goto yy21;
yy25:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy32;
		if (yych == 'r') goto yy32;
		goto yy21;
yy26:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy33;
		if (yych == 'e') goto yy33;
		goto yy21;
yy27:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy34;
		if (yych == 'b') goto yy34;
		goto yy21;
yy28:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy35;
		if (yych == 'l') goto yy35;
		goto yy21;
yy29:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy36;
		if (yych == 's') goto yy36;
		goto yy21;
yy30:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy37;
		if (yych == 't') goto yy37;
		goto yy21;
yy31:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy38;
		if (yych == 't') goto yy38;
		goto yy21;
yy32:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy40;
		if (yych == 'e') goto yy40;
		goto yy21;
yy33:
		yych = *++lex->cursor;
		if (yych == 'V') goto yy41;
		if (yych == 'v') goto yy41;
		goto yy21;
yy34:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy42;
		if (yych == 'l') goto yy42;
		goto yy21;
yy35:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy43;
		if (yych == 'd') goto yy43;
		goto yy21;
yy36:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy44;
		if (yych == 't') goto yy44;
		goto yy21;
yy37:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy45;
		if (yych == 'c') goto yy45;
		goto yy21;
yy38:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 140 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_NEXT;
}
#line 361 "/opt/src/php-cmark/src/cql_lexer.c"
yy40:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy46;
		if (yych == 'n') goto yy46;
		goto yy21;
yy41:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy47;
		if (yych == 'i') goto yy47;
		goto yy21;
yy42:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy48;
		if (yych == 'i') goto yy48;
		goto yy21;
yy43:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy49;
		if (yych == 'r') goto yy49;
		goto yy21;
yy44:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy50;
		if (yych == 'c') goto yy50;
		goto yy21;
yy45:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy51;
		if (yych == 'h') goto yy51;
		goto yy21;
yy46:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy52;
		if (yych == 't') goto yy52;
		goto yy21;
yy47:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy54;
		if (yych == 'o') goto yy54;
		goto yy21;
yy48:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy55;
		if (yych == 'n') goto yy55;
		goto yy21;
yy49:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy56;
		if (yych == 'e') goto yy56;
		goto yy21;
yy50:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy57;
		if (yych == 'h') goto yy57;
		goto yy21;
yy51:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy58;
		if (yych == 'i') goto yy58;
		goto yy21;
yy52:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 134 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_PARENT;
}
#line 431 "/opt/src/php-cmark/src/cql_lexer.c"
yy54:
		yych = *++lex->cursor;
		if (yych == 'U') goto yy59;
		if (yych == 'u') goto yy59;
		goto yy21;
yy55:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy60;
		if (yych == 'g') goto yy60;
		goto yy21;
yy56:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy61;
		if (yych == 'n') goto yy61;
		goto yy21;
yy57:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy63;
		if (yych == 'i') goto yy63;
		goto yy21;
yy58:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy64;
		if (yych == 'l') goto yy64;
		goto yy21;
yy59:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy65;
		if (yych == 's') goto yy65;
		goto yy21;
yy60:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy67;
		if (yych == 's') goto yy67;
		goto yy21;
yy61:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 152 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_CHILDREN;
}
#line 476 "/opt/src/php-cmark/src/cql_lexer.c"
yy63:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy69;
		if (yych == 'l') goto yy69;
		goto yy21;
yy64:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy70;
		if (yych == 'd') goto yy70;
		goto yy21;
yy65:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 146 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_PREVIOUS;
}
#line 496 "/opt/src/php-cmark/src/cql_lexer.c"
yy67:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 158 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_SIBLINGS;
}
#line 506 "/opt/src/php-cmark/src/cql_lexer.c"
yy69:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy72;
		if (yych == 'd') goto yy72;
		goto yy21;
yy70:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 128 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_LAST_CHILD;
}
#line 521 "/opt/src/php-cmark/src/cql_lexer.c"
yy72:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 122 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_FIRST_CHILD;
}
#line 531 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_SEPARATOR:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(2);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy80;
		}
		if (yych <= '.') {
			if (yych <= '#') {
				if (yych <= 0x00) goto yy76;
				if (yych <= '"') goto yy78;
				goto yy83;
			} else {
				if (yych == '(') goto yy84;
				goto yy78;
			}
		} else {
			if (yych <= '[') {
				if (yych <= '/') goto yy86;
				if (yych <= 'Z') goto yy78;
				goto yy88;
			} else {
				if (yych <= '\\') goto yy86;
				if (yych <= ']') goto yy90;
				goto yy78;
			}
		}
yy76:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 104 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 602 "/opt/src/php-cmark/src/cql_lexer.c"
yy78:
		++lex->cursor;
yy79:
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 310 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 1;
}
#line 611 "/opt/src/php-cmark/src/cql_lexer.c"
yy80:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy80;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 108 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 624 "/opt/src/php-cmark/src/cql_lexer.c"
yy83:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy92;
		}
		goto yy79;
yy84:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 174 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE;

	return T_CONSTRAINT_START;
}
#line 640 "/opt/src/php-cmark/src/cql_lexer.c"
yy86:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 116 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_NODE;

	return T_SEPERATOR;
}
#line 650 "/opt/src/php-cmark/src/cql_lexer.c"
yy88:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 164 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_SUBQUERY_START;
}
#line 660 "/opt/src/php-cmark/src/cql_lexer.c"
yy90:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 170 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return T_SUBQUERY_END;
}
#line 668 "/opt/src/php-cmark/src/cql_lexer.c"
yy92:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy92;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 112 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 681 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_SUBQUERY:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(2);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy101;
		}
		if (yych <= '(') {
			if (yych <= '"') {
				if (yych >= 0x01) goto yy99;
			} else {
				if (yych <= '#') goto yy104;
				if (yych <= '\'') goto yy99;
				goto yy105;
			}
		} else {
			if (yych <= '[') {
				if (yych <= 'Z') goto yy99;
				goto yy107;
			} else {
				if (yych == ']') goto yy109;
				goto yy99;
			}
		}
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 104 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 748 "/opt/src/php-cmark/src/cql_lexer.c"
yy99:
		++lex->cursor;
yy100:
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 310 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 1;
}
#line 757 "/opt/src/php-cmark/src/cql_lexer.c"
yy101:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy101;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 108 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 770 "/opt/src/php-cmark/src/cql_lexer.c"
yy104:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy111;
		}
		goto yy100;
yy105:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 174 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE;

	return T_CONSTRAINT_START;
}
#line 786 "/opt/src/php-cmark/src/cql_lexer.c"
yy107:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 164 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_SUBQUERY_START;
}
#line 796 "/opt/src/php-cmark/src/cql_lexer.c"
yy109:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 170 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return T_SUBQUERY_END;
}
#line 804 "/opt/src/php-cmark/src/cql_lexer.c"
yy111:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy111;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 112 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 817 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_TYPE:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(13);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy120;
		}
		if (yych <= 'S') {
			if (yych <= 'D') {
				if (yych <= '(') {
					if (yych <= 0x00) goto yy116;
					if (yych == '#') goto yy123;
					goto yy118;
				} else {
					if (yych <= 'A') {
						if (yych <= ')') goto yy124;
						goto yy118;
					} else {
						if (yych <= 'B') goto yy126;
						if (yych <= 'C') goto yy127;
						goto yy118;
					}
				}
			} else {
				if (yych <= 'K') {
					if (yych <= 'G') {
						if (yych <= 'E') goto yy128;
						goto yy118;
					} else {
						if (yych <= 'H') goto yy129;
						if (yych <= 'I') goto yy130;
						goto yy118;
					}
				} else {
					if (yych <= 'O') {
						if (yych <= 'L') goto yy131;
						goto yy118;
					} else {
						if (yych <= 'P') goto yy132;
						if (yych <= 'R') goto yy118;
						goto yy133;
					}
				}
			}
		} else {
			if (yych <= 'i') {
				if (yych <= 'c') {
					if (yych <= 'T') goto yy134;
					if (yych <= 'a') goto yy118;
					if (yych <= 'b') goto yy126;
					goto yy127;
				} else {
					if (yych <= 'e') {
						if (yych <= 'd') goto yy118;
						goto yy128;
					} else {
						if (yych <= 'g') goto yy118;
						if (yych <= 'h') goto yy129;
						goto yy130;
					}
				}
			} else {
				if (yych <= 'r') {
					if (yych <= 'l') {
						if (yych <= 'k') goto yy118;
						goto yy131;
					} else {
						if (yych == 'p') goto yy132;
						goto yy118;
					}
				} else {
					if (yych <= 't') {
						if (yych <= 's') goto yy133;
						goto yy134;
					} else {
						if (yych == '~') goto yy135;
						goto yy118;
					}
				}
			}
		}
yy116:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 104 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 942 "/opt/src/php-cmark/src/cql_lexer.c"
yy118:
		++lex->cursor;
yy119:
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 310 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 1;
}
#line 951 "/opt/src/php-cmark/src/cql_lexer.c"
yy120:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy120;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 108 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 964 "/opt/src/php-cmark/src/cql_lexer.c"
yy123:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy137;
		}
		goto yy119;
yy124:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 184 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_CONSTRAINT_END;
}
#line 980 "/opt/src/php-cmark/src/cql_lexer.c"
yy126:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'L') goto yy140;
		if (yych == 'l') goto yy140;
		goto yy119;
yy127:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych <= 'U') {
			if (yych == 'O') goto yy142;
			if (yych <= 'T') goto yy119;
			goto yy143;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy119;
				goto yy142;
			} else {
				if (yych == 'u') goto yy143;
				goto yy119;
			}
		}
yy128:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'M') goto yy144;
		if (yych == 'm') goto yy144;
		goto yy119;
yy129:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych <= 'T') {
			if (yych == 'E') goto yy145;
			if (yych <= 'S') goto yy119;
			goto yy146;
		} else {
			if (yych <= 'e') {
				if (yych <= 'd') goto yy119;
				goto yy145;
			} else {
				if (yych == 't') goto yy146;
				goto yy119;
			}
		}
yy130:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych <= 'T') {
			if (yych == 'M') goto yy147;
			if (yych <= 'S') goto yy119;
			goto yy148;
		} else {
			if (yych <= 'm') {
				if (yych <= 'l') goto yy119;
				goto yy147;
			} else {
				if (yych == 't') goto yy148;
				goto yy119;
			}
		}
yy131:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'I') goto yy149;
		if (yych == 'i') goto yy149;
		goto yy119;
yy132:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'A') goto yy150;
		if (yych == 'a') goto yy150;
		goto yy119;
yy133:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych <= 'T') {
			if (yych == 'O') goto yy151;
			if (yych <= 'S') goto yy119;
			goto yy152;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy119;
				goto yy151;
			} else {
				if (yych == 't') goto yy152;
				goto yy119;
			}
		}
yy134:
		yyaccept = 0;
		yych = *(lex->marker = ++lex->cursor);
		if (yych <= 'H') {
			if (yych == 'E') goto yy153;
			if (yych <= 'G') goto yy119;
			goto yy154;
		} else {
			if (yych <= 'e') {
				if (yych <= 'd') goto yy119;
				goto yy153;
			} else {
				if (yych == 'h') goto yy154;
				goto yy119;
			}
		}
yy135:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 180 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return T_CONSTRAINT_NEGATE;
}
#line 1092 "/opt/src/php-cmark/src/cql_lexer.c"
yy137:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy137;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 112 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 1105 "/opt/src/php-cmark/src/cql_lexer.c"
yy140:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy155;
		if (yych == 'o') goto yy155;
yy141:
		lex->cursor = lex->marker;
		if (yyaccept == 0) {
			goto yy119;
		} else {
			goto yy172;
		}
yy142:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy156;
		if (yych == 'd') goto yy156;
		goto yy141;
yy143:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy157;
		if (yych == 's') goto yy157;
		goto yy141;
yy144:
		yych = *++lex->cursor;
		if (yych == 'P') goto yy158;
		if (yych == 'p') goto yy158;
		goto yy141;
yy145:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy159;
		if (yych == 'a') goto yy159;
		goto yy141;
yy146:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy160;
		if (yych == 'm') goto yy160;
		goto yy141;
yy147:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy161;
		if (yych == 'a') goto yy161;
		goto yy141;
yy148:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy162;
		if (yych == 'e') goto yy162;
		goto yy141;
yy149:
		yych = *++lex->cursor;
		if (yych <= 'S') {
			if (yych == 'N') goto yy163;
			if (yych <= 'R') goto yy141;
			goto yy164;
		} else {
			if (yych <= 'n') {
				if (yych <= 'm') goto yy141;
				goto yy163;
			} else {
				if (yych == 's') goto yy164;
				goto yy141;
			}
		}
yy150:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy165;
		if (yych == 'r') goto yy165;
		goto yy141;
yy151:
		yych = *++lex->cursor;
		if (yych == 'F') goto yy166;
		if (yych == 'f') goto yy166;
		goto yy141;
yy152:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy167;
		if (yych == 'r') goto yy167;
		goto yy141;
yy153:
		yych = *++lex->cursor;
		if (yych == 'X') goto yy168;
		if (yych == 'x') goto yy168;
		goto yy141;
yy154:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy169;
		if (yych == 'e') goto yy169;
		goto yy141;
yy155:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy170;
		if (yych == 'c') goto yy170;
		goto yy141;
yy156:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy171;
		if (yych == 'e') goto yy171;
		goto yy141;
yy157:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy173;
		if (yych == 't') goto yy173;
		goto yy141;
yy158:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy174;
		if (yych == 'h') goto yy174;
		goto yy141;
yy159:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy175;
		if (yych == 'd') goto yy175;
		goto yy141;
yy160:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy176;
		if (yych == 'l') goto yy176;
		goto yy141;
yy161:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy177;
		if (yych == 'g') goto yy177;
		goto yy141;
yy162:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy178;
		if (yych == 'm') goto yy178;
		goto yy141;
yy163:
		yych = *++lex->cursor;
		if (yych <= 'K') {
			if (yych == 'E') goto yy180;
			if (yych <= 'J') goto yy141;
			goto yy181;
		} else {
			if (yych <= 'e') {
				if (yych <= 'd') goto yy141;
				goto yy180;
			} else {
				if (yych == 'k') goto yy181;
				goto yy141;
			}
		}
yy164:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy183;
		if (yych == 't') goto yy183;
		goto yy141;
yy165:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy185;
		if (yych == 'a') goto yy185;
		goto yy141;
yy166:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy186;
		if (yych == 't') goto yy186;
		goto yy141;
yy167:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy187;
		if (yych == 'o') goto yy187;
		goto yy141;
yy168:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy188;
		if (yych == 't') goto yy188;
		goto yy141;
yy169:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy190;
		if (yych == 'm') goto yy190;
		goto yy141;
yy170:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy191;
		if (yych == 'k') goto yy191;
		goto yy141;
yy171:
		yyaccept = 1;
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'B') goto yy192;
		if (yych == 'b') goto yy192;
yy172:
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 268 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CODE;
}
#line 1295 "/opt/src/php-cmark/src/cql_lexer.c"
yy173:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy193;
		if (yych == 'o') goto yy193;
		goto yy141;
yy174:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy194;
		if (yych == 'a') goto yy194;
		goto yy141;
yy175:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy195;
		if (yych == 'i') goto yy195;
		goto yy141;
yy176:
		yych = *++lex->cursor;
		if (yych <= 'I') {
			if (yych == 'B') goto yy196;
			if (yych <= 'H') goto yy141;
			goto yy197;
		} else {
			if (yych <= 'b') {
				if (yych <= 'a') goto yy141;
				goto yy196;
			} else {
				if (yych == 'i') goto yy197;
				goto yy141;
			}
		}
yy177:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy198;
		if (yych == 'e') goto yy198;
		goto yy141;
yy178:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 208 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_ITEM;
}
#line 1340 "/opt/src/php-cmark/src/cql_lexer.c"
yy180:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy200;
		if (yych == 'b') goto yy200;
		goto yy141;
yy181:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 298 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_LINK;
}
#line 1355 "/opt/src/php-cmark/src/cql_lexer.c"
yy183:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 202 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_LIST;
}
#line 1365 "/opt/src/php-cmark/src/cql_lexer.c"
yy185:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy201;
		if (yych == 'g') goto yy201;
		goto yy141;
yy186:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy202;
		if (yych == 'b') goto yy202;
		goto yy141;
yy187:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy203;
		if (yych == 'n') goto yy203;
		goto yy141;
yy188:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 250 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_TEXT;
}
#line 1390 "/opt/src/php-cmark/src/cql_lexer.c"
yy190:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy204;
		if (yych == 'a') goto yy204;
		goto yy141;
yy191:
		yych = *++lex->cursor;
		if (yych == 'Q') goto yy205;
		if (yych == 'q') goto yy205;
		goto yy141;
yy192:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy206;
		if (yych == 'l') goto yy206;
		goto yy141;
yy193:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy207;
		if (yych == 'm') goto yy207;
		goto yy141;
yy194:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy208;
		if (yych == 's') goto yy208;
		goto yy141;
yy195:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy209;
		if (yych == 'n') goto yy209;
		goto yy141;
yy196:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy210;
		if (yych == 'l') goto yy210;
		goto yy141;
yy197:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy211;
		if (yych == 'n') goto yy211;
		goto yy141;
yy198:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 304 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_IMAGE;
}
#line 1440 "/opt/src/php-cmark/src/cql_lexer.c"
yy200:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy212;
		if (yych == 'r') goto yy212;
		goto yy141;
yy201:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy213;
		if (yych == 'r') goto yy213;
		goto yy141;
yy202:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy214;
		if (yych == 'r') goto yy214;
		goto yy141;
yy203:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy215;
		if (yych == 'g') goto yy215;
		goto yy141;
yy204:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy217;
		if (yych == 't') goto yy217;
		goto yy141;
yy205:
		yych = *++lex->cursor;
		if (yych == 'U') goto yy218;
		if (yych == 'u') goto yy218;
		goto yy141;
yy206:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy219;
		if (yych == 'o') goto yy219;
		goto yy141;
yy207:
		yych = *++lex->cursor;
		if (yych <= 'I') {
			if (yych == 'B') goto yy220;
			if (yych <= 'H') goto yy141;
			goto yy221;
		} else {
			if (yych <= 'b') {
				if (yych <= 'a') goto yy141;
				goto yy220;
			} else {
				if (yych == 'i') goto yy221;
				goto yy141;
			}
		}
yy208:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy222;
		if (yych == 'i') goto yy222;
		goto yy141;
yy209:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy223;
		if (yych == 'g') goto yy223;
		goto yy141;
yy210:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy225;
		if (yych == 'o') goto yy225;
		goto yy141;
yy211:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy226;
		if (yych == 'l') goto yy226;
		goto yy141;
yy212:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy227;
		if (yych == 'e') goto yy227;
		goto yy141;
yy213:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy228;
		if (yych == 'a') goto yy228;
		goto yy141;
yy214:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy229;
		if (yych == 'e') goto yy229;
		goto yy141;
yy215:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 292 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_STRONG;
}
#line 1535 "/opt/src/php-cmark/src/cql_lexer.c"
yy217:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy230;
		if (yych == 'i') goto yy230;
		goto yy141;
yy218:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy231;
		if (yych == 'o') goto yy231;
		goto yy141;
yy219:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy232;
		if (yych == 'c') goto yy232;
		goto yy141;
yy220:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy233;
		if (yych == 'l') goto yy233;
		goto yy141;
yy221:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy234;
		if (yych == 'n') goto yy234;
		goto yy141;
yy222:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy235;
		if (yych == 's') goto yy235;
		goto yy141;
yy223:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 238 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_HEADING;
}
#line 1575 "/opt/src/php-cmark/src/cql_lexer.c"
yy225:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy237;
		if (yych == 'c') goto yy237;
		goto yy141;
yy226:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy238;
		if (yych == 'i') goto yy238;
		goto yy141;
yy227:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy239;
		if (yych == 'a') goto yy239;
		goto yy141;
yy228:
		yych = *++lex->cursor;
		if (yych == 'P') goto yy240;
		if (yych == 'p') goto yy240;
		goto yy141;
yy229:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy241;
		if (yych == 'a') goto yy241;
		goto yy141;
yy230:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy242;
		if (yych == 'c') goto yy242;
		goto yy141;
yy231:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy243;
		if (yych == 't') goto yy243;
		goto yy141;
yy232:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy244;
		if (yych == 'k') goto yy244;
		goto yy141;
yy233:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy246;
		if (yych == 'o') goto yy246;
		goto yy141;
yy234:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy247;
		if (yych == 'l') goto yy247;
		goto yy141;
yy235:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 286 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_EMPHASIS;
}
#line 1635 "/opt/src/php-cmark/src/cql_lexer.c"
yy237:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy248;
		if (yych == 'k') goto yy248;
		goto yy141;
yy238:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy250;
		if (yych == 'n') goto yy250;
		goto yy141;
yy239:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy251;
		if (yych == 'k') goto yy251;
		goto yy141;
yy240:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy253;
		if (yych == 'h') goto yy253;
		goto yy141;
yy241:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy255;
		if (yych == 'k') goto yy255;
		goto yy141;
yy242:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy257;
		if (yych == 'b') goto yy257;
		goto yy141;
yy243:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy258;
		if (yych == 'e') goto yy258;
		goto yy141;
yy244:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 214 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CODE_BLOCK;
}
#line 1680 "/opt/src/php-cmark/src/cql_lexer.c"
yy246:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy260;
		if (yych == 'c') goto yy260;
		goto yy141;
yy247:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy261;
		if (yych == 'i') goto yy261;
		goto yy141;
yy248:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 220 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_HTML_BLOCK;
}
#line 1700 "/opt/src/php-cmark/src/cql_lexer.c"
yy250:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy262;
		if (yych == 'e') goto yy262;
		goto yy141;
yy251:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 262 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_LINE_BREAK;
}
#line 1715 "/opt/src/php-cmark/src/cql_lexer.c"
yy253:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 232 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_PARAGRAPH;
}
#line 1725 "/opt/src/php-cmark/src/cql_lexer.c"
yy255:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 256 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_SOFT_BREAK;
}
#line 1735 "/opt/src/php-cmark/src/cql_lexer.c"
yy257:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy264;
		if (yych == 'r') goto yy264;
		goto yy141;
yy258:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 196 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_BLOCK_QUOTE;
}
#line 1750 "/opt/src/php-cmark/src/cql_lexer.c"
yy260:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy265;
		if (yych == 'k') goto yy265;
		goto yy141;
yy261:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy267;
		if (yych == 'n') goto yy267;
		goto yy141;
yy262:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 274 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_HTML_INLINE;
}
#line 1770 "/opt/src/php-cmark/src/cql_lexer.c"
yy264:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy268;
		if (yych == 'e') goto yy268;
		goto yy141;
yy265:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 226 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CUSTOM_BLOCK;
}
#line 1785 "/opt/src/php-cmark/src/cql_lexer.c"
yy267:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy269;
		if (yych == 'e') goto yy269;
		goto yy141;
yy268:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy271;
		if (yych == 'a') goto yy271;
		goto yy141;
yy269:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 280 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CUSTOM_INLINE;
}
#line 1805 "/opt/src/php-cmark/src/cql_lexer.c"
yy271:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy272;
		if (yych != 'k') goto yy141;
yy272:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 244 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_THEMATIC_BREAK;
}
#line 1819 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_TYPE_SEPARATOR:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(2);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy280;
		}
		if (yych <= '(') {
			if (yych <= 0x00) goto yy276;
			if (yych == '#') goto yy283;
			goto yy278;
		} else {
			if (yych <= ')') goto yy284;
			if (yych == '|') goto yy286;
			goto yy278;
		}
yy276:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 104 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 1879 "/opt/src/php-cmark/src/cql_lexer.c"
yy278:
		++lex->cursor;
yy279:
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 310 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 1;
}
#line 1888 "/opt/src/php-cmark/src/cql_lexer.c"
yy280:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy280;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 108 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 1901 "/opt/src/php-cmark/src/cql_lexer.c"
yy283:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy288;
		}
		goto yy279;
yy284:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 184 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_CONSTRAINT_END;
}
#line 1917 "/opt/src/php-cmark/src/cql_lexer.c"
yy286:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 190 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE;

	return T_TYPE_SEPARATOR;
}
#line 1927 "/opt/src/php-cmark/src/cql_lexer.c"
yy288:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy288;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 112 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 1940 "/opt/src/php-cmark/src/cql_lexer.c"
	}
}
#line 314 "/opt/src/php-cmark/src/cql_lexer.l"

}
