/* Generated by re2c 0.16 */
#line 1 "/opt/src/php-cmark/src/cql_lexer.l"
/*
 * cql_lexer.l
 */

#include <src/cql.h>
#include <src/cql_parser.h>

#line 11 "/opt/src/php-cmark/src/cql_lexer.c"

enum cql_lex_state_t {
	ST_LOOKING_FOR_SEPARATOR,
	ST_LOOKING_FOR_NODE,
	ST_LOOKING_FOR_SUBQUERY,
	ST_LOOKING_FOR_TYPE,
	ST_LOOKING_FOR_TYPE_SEPARATOR,
};

#line 8 "/opt/src/php-cmark/src/cql_lexer.l"
struct _cql_lex_t {
        unsigned int len;
        unsigned char *text;
        unsigned char *cursor;
        unsigned char *marker;
        unsigned char *ctxmarker;
        int state;
};

cql_lex_t* cql_lex_init (unsigned char *text, size_t length) {
	cql_lex_t *lex;

	if (!length || !text || !*text) {
		return NULL;
	}

	lex = (cql_lex_t*) calloc(1, sizeof(cql_lex_t));

	if (!lex) {
		return NULL;
	}

	lex->state = ST_LOOKING_FOR_SEPARATOR;
	lex->text  = lex->cursor = text;
	lex->len   = length;

	return lex;
}

unsigned char* cql_lex_cursor(cql_lex_t *lex, int offset) {
	return lex->cursor + offset;
}

void cql_lex_free(cql_lex_t *lex) {
	if (!lex) {
		return;
	}

	free(lex);
}

int cql_lex (cql_ast_t *yylval, cql_lex_t *lex) {

restart:
	lex->text = lex->cursor;


#line 69 "/opt/src/php-cmark/src/cql_lexer.c"
{
	unsigned char yych;
	if (lex->state < 2) {
		if (lex->state < 1) {
			goto yyc_ST_LOOKING_FOR_SEPARATOR;
		} else {
			goto yyc_ST_LOOKING_FOR_NODE;
		}
	} else {
		if (lex->state < 3) {
			goto yyc_ST_LOOKING_FOR_SUBQUERY;
		} else {
			if (lex->state < 4) {
				goto yyc_ST_LOOKING_FOR_TYPE;
			} else {
				goto yyc_ST_LOOKING_FOR_TYPE_SEPARATOR;
			}
		}
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_NODE:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(10);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy6;
		}
		if (yych <= 'R') {
			if (yych <= 'F') {
				if (yych <= '#') {
					if (yych <= 0x00) goto yy4;
					if (yych >= '#') goto yy9;
				} else {
					if (yych == 'C') goto yy10;
					if (yych >= 'F') goto yy11;
				}
			} else {
				if (yych <= 'M') {
					if (yych == 'L') goto yy12;
				} else {
					if (yych <= 'N') goto yy13;
					if (yych == 'P') goto yy14;
				}
			}
		} else {
			if (yych <= 'l') {
				if (yych <= 'c') {
					if (yych <= 'S') goto yy15;
					if (yych >= 'c') goto yy10;
				} else {
					if (yych == 'f') goto yy11;
					if (yych >= 'l') goto yy12;
				}
			} else {
				if (yych <= 'o') {
					if (yych == 'n') goto yy13;
				} else {
					if (yych <= 'p') goto yy14;
					if (yych == 's') goto yy15;
				}
			}
		}
yy3:
yy4:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 102 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 174 "/opt/src/php-cmark/src/cql_lexer.c"
yy6:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy6;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 106 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 187 "/opt/src/php-cmark/src/cql_lexer.c"
yy9:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy16;
		}
		goto yy3;
yy10:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy19;
		if (yych == 'h') goto yy19;
		goto yy3;
yy11:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy20;
		if (yych == 'i') goto yy20;
		goto yy3;
yy12:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy21;
		if (yych == 'a') goto yy21;
		goto yy3;
yy13:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy22;
		if (yych == 'e') goto yy22;
		goto yy3;
yy14:
		yych = *++lex->cursor;
		if (yych <= 'R') {
			if (yych == 'A') goto yy23;
			if (yych <= 'Q') goto yy3;
			goto yy24;
		} else {
			if (yych <= 'a') {
				if (yych <= '`') goto yy3;
				goto yy23;
			} else {
				if (yych == 'r') goto yy24;
				goto yy3;
			}
		}
yy15:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy25;
		if (yych == 'i') goto yy25;
		goto yy3;
yy16:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy16;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 110 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 246 "/opt/src/php-cmark/src/cql_lexer.c"
yy19:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy26;
		if (yych == 'i') goto yy26;
		goto yy3;
yy20:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy27;
		if (yych == 'r') goto yy27;
		goto yy3;
yy21:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy28;
		if (yych == 's') goto yy28;
		goto yy3;
yy22:
		yych = *++lex->cursor;
		if (yych == 'X') goto yy29;
		if (yych == 'x') goto yy29;
		goto yy3;
yy23:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy30;
		if (yych == 'r') goto yy30;
		goto yy3;
yy24:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy31;
		if (yych == 'e') goto yy31;
		goto yy3;
yy25:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy32;
		if (yych == 'b') goto yy32;
		goto yy3;
yy26:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy33;
		if (yych == 'l') goto yy33;
		goto yy3;
yy27:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy34;
		if (yych == 's') goto yy34;
		goto yy3;
yy28:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy35;
		if (yych == 't') goto yy35;
		goto yy3;
yy29:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy36;
		if (yych == 't') goto yy36;
		goto yy3;
yy30:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy38;
		if (yych == 'e') goto yy38;
		goto yy3;
yy31:
		yych = *++lex->cursor;
		if (yych == 'V') goto yy39;
		if (yych == 'v') goto yy39;
		goto yy3;
yy32:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy40;
		if (yych == 'l') goto yy40;
		goto yy3;
yy33:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy41;
		if (yych == 'd') goto yy41;
		goto yy3;
yy34:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy42;
		if (yych == 't') goto yy42;
		goto yy3;
yy35:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy43;
		if (yych == 'c') goto yy43;
		goto yy3;
yy36:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 138 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_NEXT;
}
#line 341 "/opt/src/php-cmark/src/cql_lexer.c"
yy38:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy44;
		if (yych == 'n') goto yy44;
		goto yy3;
yy39:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy45;
		if (yych == 'i') goto yy45;
		goto yy3;
yy40:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy46;
		if (yych == 'i') goto yy46;
		goto yy3;
yy41:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy47;
		if (yych == 'r') goto yy47;
		goto yy3;
yy42:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy48;
		if (yych == 'c') goto yy48;
		goto yy3;
yy43:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy49;
		if (yych == 'h') goto yy49;
		goto yy3;
yy44:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy50;
		if (yych == 't') goto yy50;
		goto yy3;
yy45:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy52;
		if (yych == 'o') goto yy52;
		goto yy3;
yy46:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy53;
		if (yych == 'n') goto yy53;
		goto yy3;
yy47:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy54;
		if (yych == 'e') goto yy54;
		goto yy3;
yy48:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy55;
		if (yych == 'h') goto yy55;
		goto yy3;
yy49:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy56;
		if (yych == 'i') goto yy56;
		goto yy3;
yy50:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 132 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_PARENT;
}
#line 411 "/opt/src/php-cmark/src/cql_lexer.c"
yy52:
		yych = *++lex->cursor;
		if (yych == 'U') goto yy57;
		if (yych == 'u') goto yy57;
		goto yy3;
yy53:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy58;
		if (yych == 'g') goto yy58;
		goto yy3;
yy54:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy59;
		if (yych == 'n') goto yy59;
		goto yy3;
yy55:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy61;
		if (yych == 'i') goto yy61;
		goto yy3;
yy56:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy62;
		if (yych == 'l') goto yy62;
		goto yy3;
yy57:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy63;
		if (yych == 's') goto yy63;
		goto yy3;
yy58:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy65;
		if (yych == 's') goto yy65;
		goto yy3;
yy59:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 150 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_CHILDREN;
}
#line 456 "/opt/src/php-cmark/src/cql_lexer.c"
yy61:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy67;
		if (yych == 'l') goto yy67;
		goto yy3;
yy62:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy68;
		if (yych == 'd') goto yy68;
		goto yy3;
yy63:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 144 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_PREVIOUS;
}
#line 476 "/opt/src/php-cmark/src/cql_lexer.c"
yy65:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 156 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_SIBLINGS;
}
#line 486 "/opt/src/php-cmark/src/cql_lexer.c"
yy67:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy70;
		if (yych == 'd') goto yy70;
		goto yy3;
yy68:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 126 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_LAST_CHILD;
}
#line 501 "/opt/src/php-cmark/src/cql_lexer.c"
yy70:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 120 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_FIRST_CHILD;
}
#line 511 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_SEPARATOR:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(2);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy77;
		}
		if (yych <= '.') {
			if (yych <= '#') {
				if (yych <= 0x00) goto yy75;
				if (yych >= '#') goto yy80;
			} else {
				if (yych == '(') goto yy81;
			}
		} else {
			if (yych <= '[') {
				if (yych <= '/') goto yy83;
				if (yych >= '[') goto yy85;
			} else {
				if (yych <= '\\') goto yy83;
				if (yych <= ']') goto yy87;
			}
		}
yy74:
yy75:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 102 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 579 "/opt/src/php-cmark/src/cql_lexer.c"
yy77:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy77;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 106 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 592 "/opt/src/php-cmark/src/cql_lexer.c"
yy80:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy89;
		}
		goto yy74;
yy81:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 172 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE;

	return T_CONSTRAINT_START;
}
#line 608 "/opt/src/php-cmark/src/cql_lexer.c"
yy83:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 114 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_NODE;

	return T_SEPERATOR;
}
#line 618 "/opt/src/php-cmark/src/cql_lexer.c"
yy85:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 162 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_SUBQUERY_START;
}
#line 628 "/opt/src/php-cmark/src/cql_lexer.c"
yy87:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 168 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return T_SUBQUERY_END;
}
#line 636 "/opt/src/php-cmark/src/cql_lexer.c"
yy89:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy89;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 110 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 649 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_SUBQUERY:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(2);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy97;
		}
		if (yych <= '(') {
			if (yych <= '"') {
				if (yych <= 0x00) goto yy95;
			} else {
				if (yych <= '#') goto yy100;
				if (yych >= '(') goto yy101;
			}
		} else {
			if (yych <= '[') {
				if (yych >= '[') goto yy103;
			} else {
				if (yych == ']') goto yy105;
			}
		}
yy94:
yy95:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 102 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 715 "/opt/src/php-cmark/src/cql_lexer.c"
yy97:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy97;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 106 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 728 "/opt/src/php-cmark/src/cql_lexer.c"
yy100:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy107;
		}
		goto yy94;
yy101:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 172 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE;

	return T_CONSTRAINT_START;
}
#line 744 "/opt/src/php-cmark/src/cql_lexer.c"
yy103:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 162 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SEPARATOR;

	return T_SUBQUERY_START;
}
#line 754 "/opt/src/php-cmark/src/cql_lexer.c"
yy105:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 168 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return T_SUBQUERY_END;
}
#line 762 "/opt/src/php-cmark/src/cql_lexer.c"
yy107:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy107;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 110 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 775 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_TYPE:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(13);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy115;
		}
		if (yych <= 'S') {
			if (yych <= 'D') {
				if (yych <= '(') {
					if (yych <= 0x00) goto yy113;
					if (yych == '#') goto yy118;
				} else {
					if (yych <= 'A') {
						if (yych <= ')') goto yy119;
					} else {
						if (yych <= 'B') goto yy121;
						if (yych <= 'C') goto yy122;
					}
				}
			} else {
				if (yych <= 'K') {
					if (yych <= 'G') {
						if (yych <= 'E') goto yy123;
					} else {
						if (yych <= 'H') goto yy124;
						if (yych <= 'I') goto yy125;
					}
				} else {
					if (yych <= 'O') {
						if (yych <= 'L') goto yy126;
					} else {
						if (yych <= 'P') goto yy127;
						if (yych >= 'S') goto yy128;
					}
				}
			}
		} else {
			if (yych <= 'i') {
				if (yych <= 'c') {
					if (yych <= 'T') goto yy129;
					if (yych <= 'a') goto yy112;
					if (yych <= 'b') goto yy121;
					goto yy122;
				} else {
					if (yych <= 'e') {
						if (yych >= 'e') goto yy123;
					} else {
						if (yych <= 'g') goto yy112;
						if (yych <= 'h') goto yy124;
						goto yy125;
					}
				}
			} else {
				if (yych <= 'r') {
					if (yych <= 'l') {
						if (yych >= 'l') goto yy126;
					} else {
						if (yych == 'p') goto yy127;
					}
				} else {
					if (yych <= 't') {
						if (yych <= 's') goto yy128;
						goto yy129;
					} else {
						if (yych == '~') goto yy130;
					}
				}
			}
		}
yy112:
		lex->cursor = lex->marker;
		goto yy166;
yy113:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 102 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 892 "/opt/src/php-cmark/src/cql_lexer.c"
yy115:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy115;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 106 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 905 "/opt/src/php-cmark/src/cql_lexer.c"
yy118:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy132;
		}
		goto yy112;
yy119:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 182 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_CONSTRAINT_END;
}
#line 921 "/opt/src/php-cmark/src/cql_lexer.c"
yy121:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy135;
		if (yych == 'l') goto yy135;
		goto yy112;
yy122:
		yych = *++lex->cursor;
		if (yych <= 'U') {
			if (yych == 'O') goto yy136;
			if (yych <= 'T') goto yy112;
			goto yy137;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy112;
				goto yy136;
			} else {
				if (yych == 'u') goto yy137;
				goto yy112;
			}
		}
yy123:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy138;
		if (yych == 'm') goto yy138;
		goto yy112;
yy124:
		yych = *++lex->cursor;
		if (yych <= 'T') {
			if (yych == 'E') goto yy139;
			if (yych <= 'S') goto yy112;
			goto yy140;
		} else {
			if (yych <= 'e') {
				if (yych <= 'd') goto yy112;
				goto yy139;
			} else {
				if (yych == 't') goto yy140;
				goto yy112;
			}
		}
yy125:
		yych = *++lex->cursor;
		if (yych <= 'T') {
			if (yych == 'M') goto yy141;
			if (yych <= 'S') goto yy112;
			goto yy142;
		} else {
			if (yych <= 'm') {
				if (yych <= 'l') goto yy112;
				goto yy141;
			} else {
				if (yych == 't') goto yy142;
				goto yy112;
			}
		}
yy126:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy143;
		if (yych == 'i') goto yy143;
		goto yy112;
yy127:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy144;
		if (yych == 'a') goto yy144;
		goto yy112;
yy128:
		yych = *++lex->cursor;
		if (yych <= 'T') {
			if (yych == 'O') goto yy145;
			if (yych <= 'S') goto yy112;
			goto yy146;
		} else {
			if (yych <= 'o') {
				if (yych <= 'n') goto yy112;
				goto yy145;
			} else {
				if (yych == 't') goto yy146;
				goto yy112;
			}
		}
yy129:
		yych = *++lex->cursor;
		if (yych <= 'H') {
			if (yych == 'E') goto yy147;
			if (yych <= 'G') goto yy112;
			goto yy148;
		} else {
			if (yych <= 'e') {
				if (yych <= 'd') goto yy112;
				goto yy147;
			} else {
				if (yych == 'h') goto yy148;
				goto yy112;
			}
		}
yy130:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 178 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return T_CONSTRAINT_NEGATE;
}
#line 1024 "/opt/src/php-cmark/src/cql_lexer.c"
yy132:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy132;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 110 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 1037 "/opt/src/php-cmark/src/cql_lexer.c"
yy135:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy149;
		if (yych == 'o') goto yy149;
		goto yy112;
yy136:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy150;
		if (yych == 'd') goto yy150;
		goto yy112;
yy137:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy151;
		if (yych == 's') goto yy151;
		goto yy112;
yy138:
		yych = *++lex->cursor;
		if (yych == 'P') goto yy152;
		if (yych == 'p') goto yy152;
		goto yy112;
yy139:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy153;
		if (yych == 'a') goto yy153;
		goto yy112;
yy140:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy154;
		if (yych == 'm') goto yy154;
		goto yy112;
yy141:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy155;
		if (yych == 'a') goto yy155;
		goto yy112;
yy142:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy156;
		if (yych == 'e') goto yy156;
		goto yy112;
yy143:
		yych = *++lex->cursor;
		if (yych <= 'S') {
			if (yych == 'N') goto yy157;
			if (yych <= 'R') goto yy112;
			goto yy158;
		} else {
			if (yych <= 'n') {
				if (yych <= 'm') goto yy112;
				goto yy157;
			} else {
				if (yych == 's') goto yy158;
				goto yy112;
			}
		}
yy144:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy159;
		if (yych == 'r') goto yy159;
		goto yy112;
yy145:
		yych = *++lex->cursor;
		if (yych == 'F') goto yy160;
		if (yych == 'f') goto yy160;
		goto yy112;
yy146:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy161;
		if (yych == 'r') goto yy161;
		goto yy112;
yy147:
		yych = *++lex->cursor;
		if (yych == 'X') goto yy162;
		if (yych == 'x') goto yy162;
		goto yy112;
yy148:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy163;
		if (yych == 'e') goto yy163;
		goto yy112;
yy149:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy164;
		if (yych == 'c') goto yy164;
		goto yy112;
yy150:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy165;
		if (yych == 'e') goto yy165;
		goto yy112;
yy151:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy167;
		if (yych == 't') goto yy167;
		goto yy112;
yy152:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy168;
		if (yych == 'h') goto yy168;
		goto yy112;
yy153:
		yych = *++lex->cursor;
		if (yych == 'D') goto yy169;
		if (yych == 'd') goto yy169;
		goto yy112;
yy154:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy170;
		if (yych == 'l') goto yy170;
		goto yy112;
yy155:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy171;
		if (yych == 'g') goto yy171;
		goto yy112;
yy156:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy172;
		if (yych == 'm') goto yy172;
		goto yy112;
yy157:
		yych = *++lex->cursor;
		if (yych <= 'K') {
			if (yych == 'E') goto yy174;
			if (yych <= 'J') goto yy112;
			goto yy175;
		} else {
			if (yych <= 'e') {
				if (yych <= 'd') goto yy112;
				goto yy174;
			} else {
				if (yych == 'k') goto yy175;
				goto yy112;
			}
		}
yy158:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy177;
		if (yych == 't') goto yy177;
		goto yy112;
yy159:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy179;
		if (yych == 'a') goto yy179;
		goto yy112;
yy160:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy180;
		if (yych == 't') goto yy180;
		goto yy112;
yy161:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy181;
		if (yych == 'o') goto yy181;
		goto yy112;
yy162:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy182;
		if (yych == 't') goto yy182;
		goto yy112;
yy163:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy184;
		if (yych == 'm') goto yy184;
		goto yy112;
yy164:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy185;
		if (yych == 'k') goto yy185;
		goto yy112;
yy165:
		yych = *(lex->marker = ++lex->cursor);
		if (yych == 'B') goto yy186;
		if (yych == 'b') goto yy186;
yy166:
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 266 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CODE;
}
#line 1220 "/opt/src/php-cmark/src/cql_lexer.c"
yy167:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy187;
		if (yych == 'o') goto yy187;
		goto yy112;
yy168:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy188;
		if (yych == 'a') goto yy188;
		goto yy112;
yy169:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy189;
		if (yych == 'i') goto yy189;
		goto yy112;
yy170:
		yych = *++lex->cursor;
		if (yych <= 'I') {
			if (yych == 'B') goto yy190;
			if (yych <= 'H') goto yy112;
			goto yy191;
		} else {
			if (yych <= 'b') {
				if (yych <= 'a') goto yy112;
				goto yy190;
			} else {
				if (yych == 'i') goto yy191;
				goto yy112;
			}
		}
yy171:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy192;
		if (yych == 'e') goto yy192;
		goto yy112;
yy172:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 206 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_ITEM;
}
#line 1265 "/opt/src/php-cmark/src/cql_lexer.c"
yy174:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy194;
		if (yych == 'b') goto yy194;
		goto yy112;
yy175:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 296 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_LINK;
}
#line 1280 "/opt/src/php-cmark/src/cql_lexer.c"
yy177:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 200 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_LIST;
}
#line 1290 "/opt/src/php-cmark/src/cql_lexer.c"
yy179:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy195;
		if (yych == 'g') goto yy195;
		goto yy112;
yy180:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy196;
		if (yych == 'b') goto yy196;
		goto yy112;
yy181:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy197;
		if (yych == 'n') goto yy197;
		goto yy112;
yy182:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 248 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_TEXT;
}
#line 1315 "/opt/src/php-cmark/src/cql_lexer.c"
yy184:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy198;
		if (yych == 'a') goto yy198;
		goto yy112;
yy185:
		yych = *++lex->cursor;
		if (yych == 'Q') goto yy199;
		if (yych == 'q') goto yy199;
		goto yy112;
yy186:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy200;
		if (yych == 'l') goto yy200;
		goto yy112;
yy187:
		yych = *++lex->cursor;
		if (yych == 'M') goto yy201;
		if (yych == 'm') goto yy201;
		goto yy112;
yy188:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy202;
		if (yych == 's') goto yy202;
		goto yy112;
yy189:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy203;
		if (yych == 'n') goto yy203;
		goto yy112;
yy190:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy204;
		if (yych == 'l') goto yy204;
		goto yy112;
yy191:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy205;
		if (yych == 'n') goto yy205;
		goto yy112;
yy192:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 302 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_IMAGE;
}
#line 1365 "/opt/src/php-cmark/src/cql_lexer.c"
yy194:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy206;
		if (yych == 'r') goto yy206;
		goto yy112;
yy195:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy207;
		if (yych == 'r') goto yy207;
		goto yy112;
yy196:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy208;
		if (yych == 'r') goto yy208;
		goto yy112;
yy197:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy209;
		if (yych == 'g') goto yy209;
		goto yy112;
yy198:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy211;
		if (yych == 't') goto yy211;
		goto yy112;
yy199:
		yych = *++lex->cursor;
		if (yych == 'U') goto yy212;
		if (yych == 'u') goto yy212;
		goto yy112;
yy200:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy213;
		if (yych == 'o') goto yy213;
		goto yy112;
yy201:
		yych = *++lex->cursor;
		if (yych <= 'I') {
			if (yych == 'B') goto yy214;
			if (yych <= 'H') goto yy112;
			goto yy215;
		} else {
			if (yych <= 'b') {
				if (yych <= 'a') goto yy112;
				goto yy214;
			} else {
				if (yych == 'i') goto yy215;
				goto yy112;
			}
		}
yy202:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy216;
		if (yych == 'i') goto yy216;
		goto yy112;
yy203:
		yych = *++lex->cursor;
		if (yych == 'G') goto yy217;
		if (yych == 'g') goto yy217;
		goto yy112;
yy204:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy219;
		if (yych == 'o') goto yy219;
		goto yy112;
yy205:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy220;
		if (yych == 'l') goto yy220;
		goto yy112;
yy206:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy221;
		if (yych == 'e') goto yy221;
		goto yy112;
yy207:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy222;
		if (yych == 'a') goto yy222;
		goto yy112;
yy208:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy223;
		if (yych == 'e') goto yy223;
		goto yy112;
yy209:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 290 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_STRONG;
}
#line 1460 "/opt/src/php-cmark/src/cql_lexer.c"
yy211:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy224;
		if (yych == 'i') goto yy224;
		goto yy112;
yy212:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy225;
		if (yych == 'o') goto yy225;
		goto yy112;
yy213:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy226;
		if (yych == 'c') goto yy226;
		goto yy112;
yy214:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy227;
		if (yych == 'l') goto yy227;
		goto yy112;
yy215:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy228;
		if (yych == 'n') goto yy228;
		goto yy112;
yy216:
		yych = *++lex->cursor;
		if (yych == 'S') goto yy229;
		if (yych == 's') goto yy229;
		goto yy112;
yy217:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 236 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_HEADING;
}
#line 1500 "/opt/src/php-cmark/src/cql_lexer.c"
yy219:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy231;
		if (yych == 'c') goto yy231;
		goto yy112;
yy220:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy232;
		if (yych == 'i') goto yy232;
		goto yy112;
yy221:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy233;
		if (yych == 'a') goto yy233;
		goto yy112;
yy222:
		yych = *++lex->cursor;
		if (yych == 'P') goto yy234;
		if (yych == 'p') goto yy234;
		goto yy112;
yy223:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy235;
		if (yych == 'a') goto yy235;
		goto yy112;
yy224:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy236;
		if (yych == 'c') goto yy236;
		goto yy112;
yy225:
		yych = *++lex->cursor;
		if (yych == 'T') goto yy237;
		if (yych == 't') goto yy237;
		goto yy112;
yy226:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy238;
		if (yych == 'k') goto yy238;
		goto yy112;
yy227:
		yych = *++lex->cursor;
		if (yych == 'O') goto yy240;
		if (yych == 'o') goto yy240;
		goto yy112;
yy228:
		yych = *++lex->cursor;
		if (yych == 'L') goto yy241;
		if (yych == 'l') goto yy241;
		goto yy112;
yy229:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 284 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_EMPHASIS;
}
#line 1560 "/opt/src/php-cmark/src/cql_lexer.c"
yy231:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy242;
		if (yych == 'k') goto yy242;
		goto yy112;
yy232:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy244;
		if (yych == 'n') goto yy244;
		goto yy112;
yy233:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy245;
		if (yych == 'k') goto yy245;
		goto yy112;
yy234:
		yych = *++lex->cursor;
		if (yych == 'H') goto yy247;
		if (yych == 'h') goto yy247;
		goto yy112;
yy235:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy249;
		if (yych == 'k') goto yy249;
		goto yy112;
yy236:
		yych = *++lex->cursor;
		if (yych == 'B') goto yy251;
		if (yych == 'b') goto yy251;
		goto yy112;
yy237:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy252;
		if (yych == 'e') goto yy252;
		goto yy112;
yy238:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 212 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CODE_BLOCK;
}
#line 1605 "/opt/src/php-cmark/src/cql_lexer.c"
yy240:
		yych = *++lex->cursor;
		if (yych == 'C') goto yy254;
		if (yych == 'c') goto yy254;
		goto yy112;
yy241:
		yych = *++lex->cursor;
		if (yych == 'I') goto yy255;
		if (yych == 'i') goto yy255;
		goto yy112;
yy242:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 218 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_HTML_BLOCK;
}
#line 1625 "/opt/src/php-cmark/src/cql_lexer.c"
yy244:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy256;
		if (yych == 'e') goto yy256;
		goto yy112;
yy245:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 260 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_LINE_BREAK;
}
#line 1640 "/opt/src/php-cmark/src/cql_lexer.c"
yy247:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 230 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_PARAGRAPH;
}
#line 1650 "/opt/src/php-cmark/src/cql_lexer.c"
yy249:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 254 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_SOFT_BREAK;
}
#line 1660 "/opt/src/php-cmark/src/cql_lexer.c"
yy251:
		yych = *++lex->cursor;
		if (yych == 'R') goto yy258;
		if (yych == 'r') goto yy258;
		goto yy112;
yy252:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 194 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_BLOCK_QUOTE;
}
#line 1675 "/opt/src/php-cmark/src/cql_lexer.c"
yy254:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy259;
		if (yych == 'k') goto yy259;
		goto yy112;
yy255:
		yych = *++lex->cursor;
		if (yych == 'N') goto yy261;
		if (yych == 'n') goto yy261;
		goto yy112;
yy256:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 272 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_HTML_INLINE;
}
#line 1695 "/opt/src/php-cmark/src/cql_lexer.c"
yy258:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy262;
		if (yych == 'e') goto yy262;
		goto yy112;
yy259:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 224 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CUSTOM_BLOCK;
}
#line 1710 "/opt/src/php-cmark/src/cql_lexer.c"
yy261:
		yych = *++lex->cursor;
		if (yych == 'E') goto yy263;
		if (yych == 'e') goto yy263;
		goto yy112;
yy262:
		yych = *++lex->cursor;
		if (yych == 'A') goto yy265;
		if (yych == 'a') goto yy265;
		goto yy112;
yy263:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 278 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_CUSTOM_INLINE;
}
#line 1730 "/opt/src/php-cmark/src/cql_lexer.c"
yy265:
		yych = *++lex->cursor;
		if (yych == 'K') goto yy266;
		if (yych != 'k') goto yy112;
yy266:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 242 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE_SEPARATOR;

	return T_TYPE_THEMATIC_BREAK;
}
#line 1744 "/opt/src/php-cmark/src/cql_lexer.c"
	}
/* *********************************** */
yyc_ST_LOOKING_FOR_TYPE_SEPARATOR:
	{
		static const unsigned char yybm[] = {
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 192,  64, 128, 128, 192, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			192, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
			128, 128, 128, 128, 128, 128, 128, 128, 
		};
		(2);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy273;
		}
		if (yych <= '(') {
			if (yych <= 0x00) goto yy271;
			if (yych == '#') goto yy276;
		} else {
			if (yych <= ')') goto yy277;
			if (yych == '|') goto yy279;
		}
yy270:
yy271:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 102 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	return 0;
}
#line 1803 "/opt/src/php-cmark/src/cql_lexer.c"
yy273:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 64) {
			goto yy273;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 106 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 1816 "/opt/src/php-cmark/src/cql_lexer.c"
yy276:
		yych = *++lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy281;
		}
		goto yy270;
yy277:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 182 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_SUBQUERY;

	return T_CONSTRAINT_END;
}
#line 1832 "/opt/src/php-cmark/src/cql_lexer.c"
yy279:
		++lex->cursor;
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 188 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	lex->state = ST_LOOKING_FOR_TYPE;

	return T_TYPE_SEPARATOR;
}
#line 1842 "/opt/src/php-cmark/src/cql_lexer.c"
yy281:
		++lex->cursor;
		(1);
		yych = *lex->cursor;
		if (yybm[0+yych] & 128) {
			goto yy281;
		}
		lex->len = (size_t) lex->cursor - (size_t) lex->text;
#line 110 "/opt/src/php-cmark/src/cql_lexer.l"
		{
	goto restart;
}
#line 1855 "/opt/src/php-cmark/src/cql_lexer.c"
	}
}
#line 308 "/opt/src/php-cmark/src/cql_lexer.l"

}
